name: "dd"
on: workflow_dispatch

jobs:
  terraform-job:
    runs-on: Linux-MaDeMi
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./1-main-module
